name: CI/CD Workflow

on: 
  push:
    branches:
      - main
      - destroy-infra

jobs:

  Build:
    if: github.ref != 'refs/heads/destroy-infra'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        make install
          
  Test:
    needs: Build
    if: github.ref != 'refs/heads/destroy-infra'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        make install
    
    - name: Lint
      run: |
        make lint
    
    - name: Format
      run: |
        make format
    
    - name: Test
      run: |
        make test
    
    - name: Start the server
      run: |
        python src/main.py & sleep 10

    - name: Load Test
      run: |
        make load-test
  
  Infra:
    needs: Test
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check if terraform-state exists
    id: check-artifact
    uses: actions/github-script@v0.9.0
    with:
      script: |
        const artifacts = await github.actions.listWorkflowRunArtifacts({
          owner: context.repo.owner,
          repo: context.repo.repo,
          run_id: context.runId
        });
        const artifactExists = artifacts.data.artifacts.some(artifact => artifact.name === 'terraform-state');
        core.setOutput('exists', artifactExists);

    - name: Download Terraform State
      uses: actions/download-artifact@v2
      with:
        name: terraform-state
        path: ./infra

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./infra

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1 
      
    - name: Terraform Apply or Destroy
      run: |
        if [ "${{ github.ref }}" = "refs/heads/destroy-infra" ]; then
          terraform destroy -auto-approve
        else
          terraform apply -auto-approve
        fi
      working-directory: ./infra
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
    
    - name: Upload Terraform State as Artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: terraform-state
        path: ./infra/terraform.tfstate

  CodeBuild:
    needs: Infra
    if: github.ref != 'refs/heads/destroy-infra'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1    
  
    - name: Start AWS CodeBuild
      run: |
        make codebuild